import math


COLOR_BLUE = (61, 128, 168)
COLOR_RED = (231, 100, 90)
COLOR_WHITE = (213, 204, 183)
COLOR_BLACK = (44, 45, 40)
COLOR_GREY = (132, 141, 149)

BLUE_CELLS = 9
RED_CELLS = 8
WHITE_CELLS = 7
BLACK_CELLS = 1
TOTAL_CELLS = sum([BLUE_CELLS, RED_CELLS, WHITE_CELLS, BLACK_CELLS])

CELLS_IN_ROW = math.sqrt(TOTAL_CELLS)
assert CELLS_IN_ROW.is_integer()
CELLS_IN_ROW = int(CELLS_IN_ROW)
CELLS_IN_COL = CELLS_IN_ROW

PX_CELL_SIDE = 100
PX_CELL_SIZE = (PX_CELL_SIDE,) * 2

PX_MAP_SIDE = PX_CELL_SIDE * CELLS_IN_ROW
PX_MAP_SIZE = (PX_MAP_SIDE,) * 2

BORDER_WIDTH = 1
BORDER_COLOR = 'white'
